language: scala
branches:
  only:
    - master
    - /^v\d+(\.\d+)+$/
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
script:
  - sbt test
  - sbt ";set scalaJSStage in Global := FullOptStage; test"
after_success:
  - 'if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./publish.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -n "$TRAVIS_TAG" ]; then bash ./publish.sh; fi'
