name: Slinky Styled Components CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        scalajs: ["0.6.33", "1.4.0"]
    steps:
      - name: Configure git to disable Windows line feeds
        run: "git config --global core.autocrlf false"
        shell: bash
      - uses: actions/checkout@master
      - name: Set up JDK 1.8 and SBT
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 1.8
      - name: Test (fastopt + fullopt)
        run: sbt +test "set scalaJSStage in Global := FullOptStage" +test
        env:
          SCALAJS_VERSION: ${{ matrix.scalajs }}
        shell: bash
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 1.8
    - run: git fetch --unshallow
    - name: Publish with SBT
      run: export JAVA_OPTS="-Xmx4g" && bash ./publish.sh
      if: github.ref == 'refs/heads/master' || github.event_name == 'release'
      env:
        encrypted_key: ${{ secrets.key }}
        encrypted_iv: ${{ secrets.iv }}
        PGP_PASSPHRASE: ${{ secrets.pgp_passphrase }}
